[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "py_oats"
version = "0.1.0"
description = "A python package to analyze correlated ionic transport in amorphous solids."
readme = "README.md"
requires-python = ">=3.10"
authors = [
  {name = "Vir Karan", email = "virkaran@berkeley.edu"},
]
dependencies = [
  "numpy",
  "scipy",
  "matplotlib",
  "pandas",
  "ase",
  "pymatgen",
  "pymatgen-analysis-diffusion",
]

[project.optional-dependencies]
charge = ["chgnet"]
